upgrade-nutyx.in some progress. Works in root account and cards user account mode as expected

diff --git a/scripts/upgrade-nutyx.in b/scripts/upgrade-nutyx.in
--- a/scripts/upgrade-nutyx.in
+++ b/scripts/upgrade-nutyx.in
@@ -21,19 +21,19 @@
 
 check_group_exist()
 {
-	(getent group "${UPGRADE_USER}") && return 0
+	(getent group "${UPGRADE_USER}" > /dev/null) && return 0
 	return 1
 }
 check_user_exist()
 {
-	(getent passwd "${UPGRADE_USER}") && return 0
+	(getent passwd "${UPGRADE_USER}" > /dev/null) && return 0
 	return 1
 }
 create_cards_user()
 {
-	check_group_exist ${UPGRADE_USER} || groupadd -g 96 ${UPGRADE_USER}
+	check_group_exist ${UPGRADE_USER} || groupadd -g ${UPGRADE_UID} ${UPGRADE_USER}
 	useradd -c "cards upgrade Service" -m \
-	-d ${UPGRADE_HOME}/${UPGRADE_USER} -g 96 -s /bin/sh -u 96 ${UPGRADE_USER}
+	-d ${UPGRADE_HOME}/${UPGRADE_USER} -g ${UPGRADE_UID} -s /bin/sh -u ${UPGRADE_UID} ${UPGRADE_USER}
 	
 }
 check_conf_exist()
@@ -45,9 +45,9 @@ generate_conf()
 {
 	check_user_exist || create_cards_user
 	mkdir -p ${UPGRADE_HOME}/${UPGRADE_USER}/pkg/depot
-	echo "version testing
+	echo "
 	
-url http://localhost
+url http://download.nutyx.org
 
 dir ${UPGRADE_HOME}/${UPGRADE_USER}${UPGRADE_DEPOT}/gui-extra
 dir ${UPGRADE_HOME}/${UPGRADE_USER}${UPGRADE_DEPOT}/gui
@@ -61,25 +61,34 @@ ${UPGRADE_HOME}/${UPGRADE_USER}${UPGRADE_CARDS_CONF}
 download_only()
 {
 	check_conf_exist || generate_conf
-	echo "cards upgrade --download-only --conf=${UPGRADE_HOME}/${UPGRADE_USER}${UPGRADE_CARDS_CONF}"
 	cards upgrade --download-only --conf=${UPGRADE_HOME}/${UPGRADE_USER}${UPGRADE_CARDS_CONF} \
 	|| return 1
 	return 0
 }
 download_ready()
 {
-	check_conf_exist || generate_conf
-	[ -f ${UPGRADE_HOME}/${UPGRADE_USER}${UPGRADE_DEPOT}/gui-extra/.PKGREPO ] || \
-	echo "cards upgrade --ready --conf=${UPGRADE_HOME}/${UPGRADE_USER}${UPGRADE_CARDS_CONF}"
-	cards upgrade --ready --conf=${UPGRADE_HOME}/${UPGRADE_USER}${UPGRADE_CARDS_CONF} && return 0
-	return 1
+	cards upgrade --ready --conf=${UPGRADE_HOME}/${UPGRADE_USER}${UPGRADE_CARDS_CONF} || return 1
+	touch ${UPGRADE_HOME}/${UPGRADE_USER}${UPGRADE_DEPOT}/${UPGRADE_READY}
+	return 0
 }
 main()
 {
-	download_ready
-	echo "cards upgrade --conf=${UPGRADE_HOME}/${UPGRADE_USER}${UPGRADE_CARDS_CONF}"
-	cards upgrade --conf=${UPGRADE_HOME}/${UPGRADE_USER}${UPGRADE_CARDS_CONF}
-	return 0
+	if [ $UID -eq 0 ]; then
+		check_user_exist ||	create_cards_user
+		check_conf_exist || generate_conf
+		[ -f ${UPGRADE_HOME}/${UPGRADE_USER}${UPGRADE_DEPOT}/${UPGRADE_READY} ] || return 0
+		cards upgrade --conf=${UPGRADE_HOME}/${UPGRADE_USER}${UPGRADE_CARDS_CONF}
+		rm  -f ${UPGRADE_HOME}/${UPGRADE_USER}${UPGRADE_DEPOT}/${UPGRADE_READY}
+		exit 0
+	fi
+	if [ "$UID" == "$UPGRADE_UID" ]; then
+		download_only
+		[ $(cards upgrade -c --conf=${UPGRADE_HOME}/${UPGRADE_USER}${UPGRADE_CARDS_CONF}) == "yes" ] && \
+		touch ${UPGRADE_HOME}/${UPGRADE_USER}${UPGRADE_DEPOT}/${UPGRADE_READY}
+		exit 0
+	fi
+	echo "Cannot run this script with $USER account"
+	exit 1
 }
 
 # Global variables
@@ -87,5 +96,7 @@ UPGRADE_USER=cards
 UPGRADE_HOME=/home
 UPGRADE_CARDS_CONF=/pkg/cards.conf
 UPGRADE_DEPOT=/pkg/depot
+UPGRADE_READY=.ready
+UPGRADE_UID="96"
 
 main "$@"
